#!/bin/bash

tee /home/rhel/solve_challenege_1.yml << EOF
---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create network backup job template
      awx.awx.job_template:
        name: "Network-Banner"
        job_type: "run"
        organization: "Default"
        inventory: Network Inventory
        project: "Network Toolkit"
        playbook: "playbooks/network_banner.yml"
        credentials:
          - "Network Credential"
        state: "present"
        controller_config_file: "/tmp/setup-scripts/controller.cfg"
EOF

sudo chown rhel:rhel /home/rhel/solve_challenege_1.yml

su - rhel -c 'ansible-playbook /home/rhel/solve_challenege_1.yml'
