version: "3"
virtualmachines:
- name: cisco
  image: red-hat-mbu/cisco-ios-csr-1731
  machine_type: n1-standard-1
- name: controller
  image: red-hat-mbu/automation-controller
  shell: /bin/su - rhel -s /bin/bash
  machine_type: n1-standard-2
