#!/bin/bash

tee /home/rhel/solve_challenge_3.yml << EOF

---
- name: Setup management Cisco IOSXE router config
  hosts: routers
  gather_facts: no

  tasks:

    - name: Add banner IOSXE
      cisco.ios.ios_banner:
        text: "First banner with Ansible"
        banner: "login"
        state: present
EOF


su - rhel -c 'ansible-navigator run /home/rhel/solve_challenge_3.yml --mode stdout'
