#!/bin/bash
#
## Fix dns resolution in automation-controller rhel9 image
echo "search $_SANDBOX_ID.svc.cluster.local." >> /etc/resolv.conf
echo "127.0.0.1 ansible-1 controller localhost" >> /etc/hosts
#
## wait for instruqt boot
set -euxo pipefail
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done
#
## set user name
USER=rhel
CONTROLLER_FQDN=controller.${_SANDBOX_ID}.svc.cluster.local

## setup rhel user
touch /etc/sudoers.d/rhel_sudoers
echo "%rhel ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/rhel_sudoers
cp -a /root/.ssh/* /home/$USER/.ssh/.
chown -R rhel:rhel /home/$USER/.ssh

## ansible home
mkdir /home/$USER/ansible
## ansible-files dir
mkdir /home/$USER/ansible-files

## ansible.cfg
echo "[defaults]" > /home/$USER/.ansible.cfg
echo "inventory = /home/$USER/ansible-files/hosts" >> /home/$USER/.ansible.cfg
echo "host_key_checking = False" >> /home/$USER/.ansible.cfg

## chown and chmod all files in rhel user home
chown -R rhel:rhel /home/$USER/ansible
chmod 777 /home/$USER/ansible
#touch /home/rhel/ansible-files/hosts
chown -R rhel:rhel /home/$USER/ansible-files

## Set controller access env variables for system
cat >/etc/environment <<EOL
CONTROLLER_HOST=controller.${_SANDBOX_ID}.svc.cluster.local
CONTROLLER_USERNAME=admin
CONTROLLER_PASSWORD='ansible123!'
CONTROLLER_VERIFY_SSL=false

EOL
cat /etc/environment
## end environment

#
# Set controller access env variables
export CONTROLLER_HOST=controller.${_SANDBOX_ID}.svc.cluster.local
export CONTROLLER_USERNAME=admin
export CONTROLLER_PASSWORD='ansible123!'
export CONTROLLER_VERIFY_SSL=false
#

## install python3 libraries needed for the Cloud Report
dnf install -y python3-pip python3-libsemanage

# Create a playbook for the user to execute
tee /tmp/aws_setup.yml << EOF
---
- name: Deploy credentials and AAP resources
  hosts: localhost
  gather_facts: false
  become: true
  vars:
    username: admin
    admin_password: ansible123!
    ansible_host: controller.${_SANDBOX_ID}.svc.cluster.local

  tasks:
  
    - name: Add SSH Controller credential to automation controller
      ansible.controller.credential:
        name: SSH Controller Credential
        description: Creds to be able to SSH the contoller_host
        organization: "Default"
        state: present
        credential_type: "Machine"
        controller_username: "{{ username }}"
        controller_password: "{{ admin_password }}"
        controller_host: "https://{{ ansible_host }}"
        validate_certs: false
        inputs:
          username: rhel
          ssh_key_data: "{{ lookup('file','/home/rhel/.ssh/id_rsa') }}"
      register: controller_try
      retries: 10
      until: controller_try is not failed

    - name: Add AWS credential to automation controller
      ansible.controller.credential:
        name: AWS_Credential
        description: Amazon Web Services
        organization: "Default"
        state: present
        credential_type: "Amazon Web Services"
        controller_username: "{{ username }}"
        controller_password: "{{ admin_password }}"
        controller_host: "https://{{ ansible_host }}"
        validate_certs: false
        inputs:
          username: "{{ lookup('env','INSTRUQT_AWS_ACCOUNT_AWSACCOUNT_AWS_ACCESS_KEY_ID') }}"
          password: "{{ lookup('env','INSTRUQT_AWS_ACCOUNT_AWSACCOUNT_AWS_SECRET_ACCESS_KEY') }}"
      register: controller_try
      retries: 10
      until: controller_try is not failed

    - name: Add EE to the controller instance
      ansible.controller.execution_environment:
        name: "AWS Execution Environment"
        image: quay.io/acme_corp/aws_ee
        controller_username: "{{ username }}"
        controller_password: "{{ admin_password }}"
        controller_host: "https://{{ ansible_host }}"
        validate_certs: false

    - name: Add project
      ansible.controller.project:
        name: "AWS Demos Project"
        description: "This is from github.com/ansible-cloud"
        organization: "Default"
        state: present
        scm_type: git
        scm_url: https://github.com/HichamMourad/awsops25
        default_environment: "Default execution environment"
        controller_username: "{{ username }}"
        controller_password: "{{ admin_password }}"
        controller_host: "https://{{ ansible_host }}"
        validate_certs: false

    - name: Delete native job template
      ansible.controller.job_template:
        name: "Demo Job Template"
        state: "absent"
        controller_username: "{{ username }}"
        controller_password: "{{ admin_password }}"
        controller_host: "https://{{ ansible_host }}"
        validate_certs: false

    - name: Create job template
      ansible.controller.job_template:
        name: "{{ item.name }}"
        job_type: "run"
        organization: "Default"
        inventory: "Demo Inventory"
        project: "AWS Demos Project"
        playbook: "{{ item.playbook }}"
        credentials:
          - "AWS_Credential"
        state: "present"
        controller_username: "{{ username }}"
        controller_password: "{{ admin_password }}"
        controller_host: "https://{{ ansible_host }}"
        validate_certs: false
        extra_vars:
          controller_host: "{{ ansible_host }}"
      with_items:
        - { playbook: 'playbooks/aws_resources.yml', name: 'Create AWS Resources' }
        - { playbook: 'playbooks/aws_instances.yml', name: 'Create AWS Instances' }

    - name: Launch a job template
      ansible.controller.job_launch:
        job_template: "Create AWS Resources"
        controller_username: "{{ username }}"
        controller_password: "{{ admin_password }}"
        controller_host: "https://{{ ansible_host }}"
        validate_certs: false
      register: job

    - name: Wait for job to finish
      ansible.controller.job_wait:
        job_id: "{{ job.id }}"
        controller_username: "{{ username }}"
        controller_password: "{{ admin_password }}"
        controller_host: "https://{{ ansible_host }}"        
        validate_certs: false

    - name: Launch a job template
      ansible.controller.job_launch:
        job_template: "Create AWS Instances"
        controller_username: "{{ username }}"
        controller_password: "{{ admin_password }}"
        controller_host: "https://{{ ansible_host }}"
        validate_certs: false
      register: job2

    - name: Wait for job2 to finish
      ansible.controller.job_wait:
        job_id: "{{ job2.id }}"
        controller_username: "{{ username }}"
        controller_password: "{{ admin_password }}"
        controller_host: "https://{{ ansible_host }}"        
        validate_certs: false

    - name: Add an AWS INVENTORY
      ansible.controller.inventory:
        name: "AWS Inventory"
        description: "Our AWS Inventory"
        organization: "Default"
        state: present
        controller_username: "{{ username }}"
        controller_password: "{{ admin_password }}"
        controller_host: "https://{{ ansible_host }}"
        validate_certs: false

    - name: Add an AWS InventorySource
      ansible.controller.inventory_source:
        name: "AWS Source"
        description: "Source for the AWS Inventory"
        inventory: "AWS Inventory"
        credential: "AWS_Credential"
        source: ec2
        overwrite: "True"
        update_on_launch: "True"
        organization: "Default"
        source_vars:
          private: "false"
          hostnames:
            - 'tag:Name'
          compose: 
            ansible_host: public_ip_address
        state: present
        controller_username: "{{ username }}"
        controller_password: "{{ admin_password }}"
        controller_host: "https://{{ ansible_host }}"
        validate_certs: false

    - name: Update a single inventory source
      ansible.controller.inventory_source_update:
        name: "AWS Source"
        inventory: "AWS Inventory"
        organization: "Default"
        controller_username: "{{ username }}"
        controller_password: "{{ admin_password }}"
        controller_host: "https://{{ ansible_host }}"
        validate_certs: false

    - name: Add ansible-1 host
      ansible.controller.host:
        name: "ansible-1"
        inventory: "Demo Inventory"
        state: present
        controller_username: "{{ username }}"
        controller_password: "{{ admin_password }}"
        controller_host: "https://{{ ansible_host }}"
        validate_certs: false
        variables:
            note: in production these passwords would be encrypted in vault
            ansible_user: rhel
            ansible_password: ansible123!
            ansible_host: controller

EOF

#
export ANSIBLE_LOCALHOST_WARNING=False
export ANSIBLE_INVENTORY_UNPARSED_WARNING=False

# Update collections path and execute the above playbook
su - rhel -c 'ANSIBLE_COLLECTIONS_PATH=/tmp/ansible-automation-platform-containerized-setup/collections/:/home/rhel/.ansible/collections/ansible_collections/ ansible-playbook /tmp/aws_setup.yml'

exit 0