---
all:
  children:
    appservers:
      hosts:
        app-0[1:2]:
    monitoring:
      hosts:
        monitor-01:
    automationcontroller:
      hosts:
        controller.acme.example.com:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/instruqt_lab
    ansible_host: lightspeed-101-controller
    ansible_user: rhel
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no -o ControlMaster=auto -o ControlPersist=60s'
    ansible_ssh_pipelining: true
    ansible_host_key_checking: false
