---
argument_specs:
  # roles/vnc_server/tasks/main.yml entry point
  main:
    short_description: The main entry point for the kiosk_mode role.
    options:
      kiosk_username:
        type: "str"
        required: false
        default: "student"
        description: "The default kiosk username."
      kiosk_password:
        type: "str"
        required: false
        default: "learn_ansible"
        description: "Password used to unlock gnome-keyring-daemon"
      kiosk_script_file:
        type: "str"
        required: false
        default: "gnome-kiosk-script"
        description: "Name of the GDM xsession Ansible template file for the Kiosk user."
      gnome_desktop_icons:
        type: "list"
        required: false
        default:
          - code
          - firefox
        description: "GNOME desktop icons based on Ansible templates with the same filename.
                      Default location for *.desktop files is {{ role_path }}/files/*.desktop.
                      Specify custom *.desktop files location by using {{ playbook_dir }} variable."
      gnome_applications:
        type: "list"
        required: false
        default:
          - gnome-kiosk-script-session
          - gnome-classic-session
          - gnome-shell-extension-desktop-icons
          - gnome-themes-extra
          - gdm
          - firefox
          - "@x-base"
          - dbus-x11
        description: "GNOME desktop and applications."
